### ISSUE TITLE
extra count in report header.

### ISSUE THREAD

**Issue by macmanes** [twestbrookunh/paladin#23]
```
head report.tsv

Count	Count %	UniProtKB ...
```

**Comment by twestbrookunh** [comment]
That's actually a second column called "Count %" that reports the percentages - when you look at it from a command line it does look like maybe it's a duplicate though since the tabs don't look uniform.  We can rename it too to be less confusing, is there a better label?  That's the column that divides the current count by the total number of alignments

**Comment by macmanes** [comment]
Maybe Percent_Map?  Not sure..

**Comment by tarunaaggarwal** [comment]
The second column reports "Count % of mapped reads"? If so, I concur when Matt...Label it "% Mapped Reads"

**Comment by tarunaaggarwal** [comment]
I hate typos!!! Anyway! Does the 2nd column report percentages of mapped reads in the Uniprot d/b? If so, I concur with Matt. Label it "% Mapped Reads"

**Comment by twestbrookunh** [comment]
Updated
