### ISSUE TITLE
Using contigs rather than reads

### ISSUE THREAD

**Issue by ameetpinto** [twestbrookunh/paladin#24]
Hi,
This is follow-up to twitter conversation with @PeroMHC.
Is the following workflow available in Paladin?
(1) Find ORF in assembled contigs
(2) map amino acid sequences to reference database
(3) The use read to contig mapping information (in SAM/BAM file) to estimate abundance of amino acid sequences per sample?

Cheers,
Ameet

**Comment by wkthomas** [comment]
It is interesting to consider and assemble-first workflow application.  I assume there is no problem to use the predicted proteins as "reads".  Supporting the use of predicted proteins would potentially enable a lot of comparative genomics.

**Comment by twestbrookunh** [comment]
As PALADIN stands right now, it has most of the internal mechanisms to accomplish #1 and #2 above ( #3 would be an addition but a very quick/easy one).  However, because of the way we are currently implementing ORF detection and post-alignment filtering, any genes present in the same contig but in a different reading frame (from the frame with the total best aligned genes on that contig) would be lost after alignment, so depending on the genomes, gene density, and contig lengths in question you would only get partial results using version 1.0.0 - though feel free to experiment and give us any feedback.  A full version is definitely doable (and without too much effort, barring unforeseen issues).  I'll mark this as an enhancement and keep it open, thanks for the questions/suggestions Ameet!

**Comment by ameetpinto** [comment]
Thanks!

**Comment by abremges** [comment]
I'd also be very interested in such a workflow – just an FYI (and as a sign of demand). 😉

**Comment by twestbrookunh** [comment]
To be tested, but using "-f 0" should accomplish this (which turns off ORF processing all together).  Closing for now
