### ISSUE TITLE
Error: [E::command_align] Reporting can only be used on prepared indices.

### ISSUE THREAD

**Issue by alejandrodesantiago** [twestbrookunh/paladin#35]
Hi, 

I am trying to use paladin align with the Uniref90 database, but I get an error:

`paladin align -t 4 -o $OUTPUT/filename $REFERENCE $INPUT`
`[E::command_align] Reporting can only be used on prepared indices`

$Reference is the path to the indexed database, however, the path contains a symlink to the actual file. Could this be the source of the error?

**Comment by twestbrookunh** [comment]
Hi - the issue is that your reference has only been indexed, but it also needs to be prepared using the "paladin prepare" command.  Normally the prepare command will download and index the reference for you (in addition to preparing it), but you can skip the download/index steps for a reference you've already manually indexed with the following command:

`paladin prepare -r2 -f <path to your reference>`

Let me know how that goes
