### ISSUE TITLE
Multithread in db creation

### ISSUE THREAD

**Issue by gundizalv** [twestbrookunh/paladin#39]
Hi

There is any possibility to add multithread to the database creation? I mean, to the command _paladin prepare_ . The db creation is very slow no matter the computer you use. 

Thanks

**Comment by twestbrookunh** [comment]
Hi @gundizalv, agreed about the indexing step - and it's only gotten worse since the size of the UniRef90 continually increases.  Adding parallel BWT construction is on the future todo list - so I hope it to have it in there at some point.  We're also thinking about providing indexed copies of the UniRef90 for download that we periodically update.  More soon...
